import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.container}>
        <header>
          <h1>i18n next-js</h1>
          <nav>
            <ul className={styles.list}>
              <li>
                <button
                  onClick={() => {
                    router.push('/blog', '/blog-en', { locale: 'en-US' });
                  }}
                >
                  <span>to en-US</span>
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    router.push('/blog', '/blog', { locale: 'pt-BR' });
                  }}
                >
                  <span>to pt-BR</span>
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    router.push('/blog', '/blog-fr', { locale: 'fr' });
                  }}
                >
                  <span>to fr</span>
                </button>
              </li>
            </ul>
          </nav>
        </header>
      </main>
    </>
  );
};

export default Home;
